---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/bumuellp/cabumtain-hook
    rev: v1.2.0
    hooks:
      - id: commit-msg
      - id: secret-scan
      - id: shell-lint
      - id: yaml-xml-lint
      - id: python-tests
      - id: trivy-config
      - id: trivy-fs
