name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-validate:
    name: Lint Hooks & Validate Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run Pre-Commit via Shared Action
        uses: bumuellp/lights-camera-bum-action/lint@main
